### ISSUE TITLE
Feature request: partial paths to also look at relative path from app.set('views')

### ISSUE THREAD

**Issue by lambertsteven** [JacksonTian/ejs-mate#12]
Would you be interested in having partial paths also look at paths relative to the app.set('views') if the partial isn't found relative to the file first? This would allow two nice features:

1. Deeply nested view directories can access partials without having to put in back directories.
2. With app.set('views') now being an array, accessing partials in a separate view path is also easier.

If you like the idea, I can write up a pull request with it along with the appropriate tests.

**Comment by JacksonTian** [comment]
closed via b5d7ce4fa54a

**Comment by JacksonTian** [comment]
```
+ ejs-mate@2.2.0
```
