### ISSUE TITLE
Support for res.write()

### ISSUE THREAD

**Issue by jpodwys** [JacksonTian/ejs-mate#14]
I basically need exactly what you've already done for res.render() to work with res.write(). Is that something you're willing to do?

**Comment by JacksonTian** [comment]
`res.render()` just can used after `res.write()`.

**Comment by jpodwys** [comment]
I should clarify--I would like to be able to hand `res.write()` a template name, just like with res.render, and have it compile the template, and partials within it, and then `res.write()` it. I want to be able to do this with multiple `res.write()` commands so that I can get the browser downloading assets and showing a header while I'm working on building the reset of the page on the server.

**Comment by jpodwys** [comment]
Also, you cannot use `res.render()` after `res.write()` because you cannot sent headers twice.

**Comment by jpodwys** [comment]
Or allow a flag to be passed that, when set to true, each partial is streamed to the client as soon as it is finished being compiled. That way the `<head>` of your HTML document could simply be a partial and you can just change all your `render` calls to `write` calls. Thoughts?

**Comment by JacksonTian** [comment]
May be PR https://github.com/JacksonTian/ejs-mate/pull/15 is you want. We export the functional, you can render the view by yourself, then use res.write to flush it to browser.

**Comment by jpodwys** [comment]
OK thanks. I wrote [express-stream](https://github.com/jpodwys/express-stream) to solve the problem.
