### ISSUE TITLE
ejs-mate Whitespace-trim mode of EJS

### ISSUE THREAD

**Issue by franceer** [JacksonTian/ejs-mate#20]
Hi,

I'm wondering if the tag <%_ used in EJS to trim whitespaces is supported by ejs-mate ? Since i'm having an issue with this tag in one of my views. Putting a for loop after opening this <%_ telling me:

"SyntaxError: Unexpected token for (...)"

**Comment by JacksonTian** [comment]
Now we depend on ejs@1.0.0, it don't have the feature.

**Comment by franceer** [comment]
Yeah sorry. I should have answered sooner. I checked the dependencies and I saw the 1.0.0 version.

Thanks for your answer
