### ISSUE TITLE
EJS 2.0.0 support

### ISSUE THREAD

**Issue by hayksaakian** [JacksonTian/ejs-mate#8]
right now this package is hardcoded for ejs 1.0.0

in my case i'm trying to use variables with ejs's "include" which is not available until ejs 2.0.0

that's why i need ejs 2.0.0 support

**Comment by JacksonTian** [comment]
"include" with variables will make the cache unavailable. Are you sure need the feature? I saw the feature was reverted at 259aa234e43fcd19e4038cd87c8f259c92f2583a.

**Comment by hayksaakian** [comment]
i didn't notice it was reverted. maybe i'm doing something unconventionally. 

i'll link my repository which uses a version of ejs before the reversion to explain my use case in a few hours.

**Comment by hayksaakian** [comment]
here's how i use include with variables

https://github.com/hayksaakian/OverRustle/blob/hnodejs/views/layout.ejs#L32

maybe i'm doing it incorrectly, and there's a better way.

**Comment by JacksonTian** [comment]
You use it incorrectly. Should like this:

```
res.render('viewname', locals);
```

The layout.ejs should be used as layout. Here is a example: https://github.com/cnodejs/nodeclub/blob/master/app.js#L55
