### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by Gank** [JacksonTian/ejs-mate#9]
Adding
```
<%= block('javascripts') %>
```
To the layout.ejs

And 
```
<% block('footer').append('<script src="/bar.js"></script>') %>
```
To a page.ejs that extends the layout will add text to the page in the following format:
```
&lt;script src=&quot;/bar.js&quot;&gt;&lt;/script&gt;
```

Am I doing something wrong here?
Thanks.

**Comment by strawhatgami** [comment]
@Gank I haven't tested it, but you should use "<%-" instead of "<%=" to avoid the content escape.
It seems that one of the two given examples in the readme is wrong, and you choiced to test the wrong :-)

**Comment by JacksonTian** [comment]
use `-` instead of `=`
